=== cbfaucher/qutils-scala/src/main/resources/com/quartz/qutilities/swing/menus/xml-menu-bar.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT menu-bar (menu)*>

<!ELEMENT menu (menu|menu-item|checkbox-menu-item|radio-menu-item|menu-separator)*>
<!ATTLIST menu label       CDATA #REQUIRED>
<!ATTLIST menu mnemonic    CDATA #IMPLIED>
<!ATTLIST menu class-name  CDATA #IMPLIED>

<!ELEMENT menu-item EMPTY>
<!ATTLIST menu-item label           CDATA #REQUIRED>
<!ATTLIST menu-item mnemonic        CDATA #IMPLIED>
<!ATTLIST menu-item action-class    CDATA #IMPLIED>
<!ATTLIST menu-item command         CDATA #IMPLIED>
<!ATTLIST menu-item accelerator     CDATA #IMPLIED>


<!ELEMENT checkbox-menu-item EMPTY>
<!ATTLIST checkbox-menu-item label           CDATA #REQUIRED>
<!ATTLIST checkbox-menu-item mnemonic        CDATA #IMPLIED>
<!ATTLIST checkbox-menu-item action-class    CDATA #IMPLIED>
<!ATTLIST checkbox-menu-item command         CDATA #IMPLIED>
<!ATTLIST checkbox-menu-item accelerator     CDATA #IMPLIED>
<!-- 'true' or 'false' -->
<!ATTLIST checkbox-menu-item state          CDATA #IMPLIED>

<!ELEMENT radio-menu-item EMPTY>
<!ATTLIST radio-menu-item label             CDATA #REQUIRED>
<!ATTLIST radio-menu-item button-group-name CDATA #REQUIRED>
<!ATTLIST radio-menu-item mnemonic          CDATA #IMPLIED>
<!ATTLIST radio-menu-item action-class      CDATA #IMPLIED>
<!ATTLIST radio-menu-item accelerator       CDATA #IMPLIED>
<!ATTLIST radio-menu-item command           CDATA #IMPLIED>

<!ELEMENT menu-separator EMPTY>

=== cbfaucher/qutils-scala/src/main/resources/com/quartz/qutilities/swing/menus/xml-menu-sample.xml
<!DOCTYPE menu-bar SYSTEM "http://www.axa.ca/dtd/xml-menu-bar.dtd">

<menu-bar>

    <menu   label="Menu 1" mnemonic="1">

        <menu-item  label="Open" mnemonic="O" command="blah" key-stroke="ctrl G" />
        <menu-item  label="Save" mnemonic="S"/>
        <menu-separator/>
        <menu-item  label="Close" mnemonic="C" action-class="com.axacanada.common.util.swing.menus.EmptyActionListener"/>
        
    </menu>

    <menu   label="Menu 2" mnemonic="2">

        <menu-item  label="Find" mnemonic="F"/>
        <menu-item  label="Replace" mnemonic="R"/>
        <checkbox-menu-item label="Check-Item" state="true"   />
        <radio-menu-item label="Single Choice" command="BLAH" action-class="com.axacanada.common.util.swing.menus.EmptyActionListener" group-name="THE-GROUP" mnemonic="A"/>
    </menu>

</menu-bar>
